swagger: '2.0'
info:
  version: v1
  title: Food-Crave APIs
  description: APIs for the Food Crave App - Swagger version
  contact: 
    name: Ritwik Chatterjee
    email: ritwik@dell.com
    
  
  
host: ritwik-dell-test.apigee.net
basePath: /food-crave/{version}
schemes:
  - http
  - https

consumes:
  - application/json
  - application/xml
  
produces:
  - application/json
  - application/xml

tags:
  - name: restaurants
    description: Find restaurants of your choice
    
paths: 
  /restaurants:
    parameters:
      - name: apikey
        in: header
        description: API Key to call the API
        required: true
        type: string
    get:
      tags:
        - restaurants
      summary: Collection of restaurants with the given search criteria - summary
      description: Collection of restaurants with the given search criteria
      parameters:
        - name: address
          in: query
          description: Address near which restaurant needs to be fetched
          required: true
          type: string
        - name: food-pref
          in: query
          description: The food/cuisine preference of the user
          required: false
          type: string
        - name: distance
          in: query
          description: The radial distance in kilometers (KMs) from the location from where to fetch the restaurants for
          required: false
          type: integer
          format: int32
          minimum: 1
          maximum: 40
          default: 40
        - $ref: '#/parameters/paging-size'
        - $ref: '#/parameters/paging-limit'
      responses:
        200:
          description: Response for resources retrieved
          schema: 
            $ref: '#/definitions/collection-response'
        400:
          $ref: '#/responses/bad-request-error'
        401:
          $ref: '#/responses/unauthorized-error'
        404:
          $ref: '#/responses/not-found-error'
        500:
          $ref: '#/responses/internal-error'
        default:
          $ref: '#/responses/default-error'

  /restaurants/{restaurantId}:
    parameters:
      - name: apikey
        in: header
        description: API Key to call the API
        required: true
        type: string
    get:
      tags:
        - restaurants
      summary: Get a specific restaurant by Id
      description: Get a specific restaurant by Id
      parameters:
        - name: restaurantId
          in: path
          description: Unique Id of the restaurant to fetch
          required: true
          type: string
      responses:
        200: 
          description: Response for resource retrieved
          schema:
            $ref: '#/definitions/item-response'
        400:
          $ref: '#/responses/bad-request-error'
        401:
          $ref: '#/responses/unauthorized-error'
        404:
          $ref: '#/responses/not-found-error'
        500:
          $ref: '#/responses/internal-error'
        default:
          $ref: '#/responses/default-error'

definitions:
  collection-response:
    type: "object"
    required: 
      - "response-status"
    properties: 
      page-size: 
        type: "number"
        example: 10
      offset: 
        type: "number"
        example: 0
      total-records: 
        type: "number"
        example: 20
      data: 
        type: "array"
        items: 
          $ref: './schema/food-crave-restaurant.schema'
      response-status: 
        $ref: './schema/response-status.schema'

  item-response:
    type: "object"
    required: 
      - "response-status"
    properties: 
      data: 
        type: "array"
        items: 
          $ref: './schema/food-crave-restaurant.schema'
      response-status: 
        $ref: './schema/response-status.schema'
        
parameters:
  paging-size:
    name: page-size
    in: query
    description: Number of restaurant details (or size of resultset) desired
    required: false
    type: integer
    format: int32
    minimum: 1
    maximum: 15
    default: 10
  paging-limit:
    name: offset
    in: query
    description: To fetch the next set of results, offset the result-set by this amount
    required: false
    type: integer
    format: int32
    minimum: 0
    default: 0

responses:
  bad-request-error:
    description: Response for badly formed request
    schema: 
      $ref: './schema/response-status.schema'
  unauthorized-error:
    description: Response for unauthorized request
    schema: 
      $ref: './schema/response-status.schema'
  not-found-error:
    description: Response for requested resource not found
    schema: 
      $ref: './schema/response-status.schema'
  internal-error:
    description: Response for other internal error
    schema: 
      $ref: './schema/response-status.schema'
  default-error:
    description: Response for other internal error
    schema: 
      $ref: './schema/response-status.schema'
